replicaCount: 1

image:
    repository: 7imbrook/life

healthEndpoint: "/health"

ingress:
    enabled: true
    hosts:
        - timbrook.tech
        - timbrook.dev
        - timbrook.life
    paths:
        - /

resources:
  limits:
   cpu: 80m
   memory: 128Mi
  requests:
   cpu: 20m
   memory: 56Mi