replicaCount: 1

image:
    repository: 7imbrook/life

healthEndpoint: "/health"

ingress:
    enabled: true
    hosts:
        - timbrook.tech 
        - timbrook.dev
    paths:
        - /

# The following is a circle CI build step for this shell
# needs to output the final image to deploy in ...?
# The standard for sharing this to build is undefined...
build:
    docker:
        - image: circleci/node
    working_directory: /home/circleci/project/frontend
    steps:
      - checkout:
          path: /home/circleci/project/ 
      - setup_remote_docker
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build Assets
          command: |
            npm run build
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build Nginx Image
          command: ../scripts/build_release.sh 7imbrook/life ./conf frontend
      - persist_to_workspace:
          root: ~/logs
          paths:
            - frontend_push.log
