---
resources:
  - name: frontend
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/frontend"
      branch: master

jobs:
  - name: release
    plan:
      - get: frontend
        trigger: true
      - task: build
        file: frontend/ci/task_build.yaml
      - task: release
        file: frontend/ci/task_release.yaml
