---
resources:
  - name: frontend
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/frontend"
      branch: master
  - name: nginx-edge-proxy
    type: docker-image
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: 7imbrook/life

jobs:
  - name: Build Assets
    plan:
      - get: frontend
        trigger: true
      - task: build
        file: frontend/ci/task_build.yaml
      - task: release
        file: frontend/ci/task_release.yaml
      - put: nginx-edge-proxy
        params:
          build: ./frontend_dist/conf
        inputs:
          - frontend_dist
